# Log params
project_name: vnav
run_name: vnav_test
eval_interval: 1
use_wandb: ture

# Train setup
seed: 0
batch_size: 192
image_size: [128, 72] # width, height, 16:9
stride: 5
pred_horizon: 16
context_size: 5
min_goal_dist: 5
max_goal_dist: 32
max_traj_len: 200

lr: 1e-4
epochs: 100 # 100
warmup_epochs: 4
num_workers: 24
encoding_size: 256
down_dims: [64, 128, 256]
num_diffusion_iters: 10

action_stats: [-24, 24, -24, 24] # [min_x, max_x, min_y, max_y]

# Datasets
datasets: [nadawalk_tokyo]

# Load checkpoint
# load_checkpoint: "vnav_debug_2023_11_19_15_38_34"