# Log params
project_name: vnav
run_name: vnav
eval_interval: 1
use_wandb: true

# Train setup
seed: 0
batch_size: 48
image_size: [256, 144] # width, height, 16:9
stride: 5
pred_horizon: 8
context_size: 5
min_goal_dist: 10
max_goal_dist: 32
max_traj_len: 200 #100
goal_mask_prob: 0.2
cam_rot_th: 10 # data point with a large camera rotation is discarded
goal_rot_th: 10 # goal vector that has a small difference with the moving direction is discarded

epochs: 100 # 20
lr: 1e-4
warmup_epochs: 4
encoding_size: 256
down_dims: [64, 128, 256]
num_diffusion_iters: 10
num_workers: 12 #12

action_stats:
  min: [-24, -24]
  max: [24, 24]

# Input/output paths
datasets_folder: /home/caoruixiang/datasets_mnt/vnav_datasets
logs_folder: /home/caoruixiang/datasets_mnt/vnav_logs
dataset_names: [nadawalk_tokyo]

# Load checkpoint
# checkpoint: "vnav_2023_12_13_18_09_53"