# Log params
project_name: vnav
run_name: vnav
eval_interval: 1
use_wandb: true

# Train setup
seed: 0
batch_size: 192
image_size: [128, 72] # width, height, 16:9
stride: 5
pred_horizon: 16
context_size: 5
min_goal_dist: 5
max_goal_dist: 32
max_traj_len: -1

epochs: 100 # 100
lr: 1e-4
warmup_epochs: 4
encoding_size: 256
down_dims: [64, 128, 256]
num_diffusion_iters: 10
num_workers: 12

action_stats:
  min: [-24, -24]
  max: [24, 24]

# Input/output paths
datasets_folder: /home/caoruixiang/datasets_mnt/vnav_datasets
logs_folder: /home/caoruixiang/datasets_mnt/vnav_logs
dataset_names: [nadawalk_tokyo]

# Load checkpoint
# checkpoint: "vnav_2023_12_11_21_23_38"