# Log params
project_name: vnav
run_name: vnav
eval_interval: 1
use_wandb: false

# Train setup
seed: 0
batch_size: 128
image_size: [128, 72] # width, height, 16:9
stride: 5
pred_horizon: 16
context_size: 5
min_goal_dist: 5
max_goal_dist: 32
max_traj_len: 50

lr: 1e-4
epochs: 1 # 100
warmup_epochs: 4
encoding_size: 256
down_dims: [64, 128, 256]
num_diffusion_iters: 10

action_stats: [-24, 24, -24, 24] # [min_x, max_x, min_y, max_y]

# Datasets
datasets_folder: /home/caoruixiang/datasets_mnt/vnav_datasets

datasets: [nadawalk_tokyo]

# Load checkpoint
# load_checkpoint: "vnav_test_2023_12_07_12_02_25"